### ISSUE TITLE
specification for the setup

### ISSUE THREAD

**Issue by yarikoptic** [dandi/nwb-healthstatus#5]
```yaml
environments:
  - name: _base_
    base-image: python
    apt:
      - libhdf5
  - name: pynwb-2.1.0
    pip:
      - pynwb==2.1.0
      - hdmf==1.1.0
  - name: pynwb-2.2.0
    pip:
      - pynwb==2.2.0
      - hdmf==1.1.0
  - name: spikeextractors-1.1.1:
      - pynwb=
      - spikeextractors=1.1.1
  - name: pynwb-latest
     pip: ["pynwb"] 
  - name: pynwb-dev
    run: pip install https://github.com/Neuro.../pynwb https://github.com/.../hdmf
data_producers:
    core:
      environments: [ 'pynwb-2.1.0', 'pynwb-2.3.0']
    emph_testing_data:
      environments: [ 'spikeextractors-1.1.1']
    extensions: # later might just sweep through all in https://nwb-extensions.github.io/
      _base-environments: ['pynwb-2.1.0']
      ndx-ibl-metadata:
         pip: ndx-ibl-metadata  # optional to map to pip name
         versions: [ '0.1.0', '1.0.0']
data_tests:
   core:
      environments: [ 'pynwb-2.1.0', 'pynwb-2.3.0', `pynwb-dev`]
     # optional: envs: to restrict to specific environments
     # maybe add urls to point to existing files in the archive, so tests could be ran against them
```

from the spec we

## populate environments

```
environments/
   <environment.name>/Dockerfile, `environment_details.yaml`
```

which we would need to probably manually (or talk via docker hub API to establish the linkage from github actions?) to create docker containers.

## produce sample files

to  be uploaded (`git annex copy` or `datalad push`) to https://gin.g-node.org/dandi/nwb-healthstatus-samples/src/master/core  under
```
<environment.name>/
   <data_producer>/
      <name, e.g. simple1>.nwb
```
or
```
<data_producer>/
    <name, e.g. simple1>[/_]<environment.name>.nwb
```
